### ISSUE TITLE
校正校閲

### ISSUE THREAD

**Issue by wass80** [kmc-jp/shinkan2016-booklet#1]
https://github.com/kmc-jp/shinkan2016-booklet/releases/download/latest/main.pdf
ここに問題をコメントしてもらえると嬉しいです

**Comment by siotouto** [comment]
> KMCとは
> 活動内容はコンピュータを使ったものを中心としているため,
> (中略)
> ・ボードゲーム
> など, 広い分野で活動しています。

中心としているため(幅を狭める理由),~など広い分野で
ってのはおかしそう.
"コンピュータを使ったものを中心として,"
なら良いと思う.
ボドゲいる？

> 日常の活動
> 部室

ホワイトボードも宣伝してもいいかもね.

> 冷暖房とこたつがあり

例年通りだしいいか・・・

> 例会
> 決議の多数決

頭痛が痛そう.そうでない読み方もできるか.
"サークルに関する提案やそれに対する質疑応答,採決をします。"
などが良さそう.

> プロジェクト

期間の長短が自由であることも付け加えたほうが良いかも.
次の章の5月5日のGo言語とか完全に1日だし.

> プロジェクトを自由に建てられる

s/建/立/

> 昨年度のプロジェクト

ツイッタークライアントとコンパイラについて,
継続中のプロジェクトがあることを書いてプロジェクトを宣伝するか,
今のように何故か現在進行形で紹介されているプロジェクトがあるか,
もう全て過去のプロジェクト扱いで過去形にするか,というのは考える余地がありそう.
プロジェクトの代表者にとって新入生に参加してほしいか,とかが影響するかなぁ.

> ゲーム
> NF

NFに関する説明付け加えたい,と思ったけどあとにあるのか
"NF(京都大学の学園祭)"とか"NF(京都大学11月祭)"とか.
"NF(詳細はP.5)"

> (画像)

この位置に画像があるなら数%マーケットの説明を上2つのいずれかに入れたほうが良さそう.
スワップかインサートかお任せしますが。

> プログラミング
> C89コンパイラを作ろう
> 冬コミに向けて C 言語のコンパイラを書こうというプロジェクトでした。現在は C90 に向
> けて製作中です。

冬コミとC90が統一感がない.
C89とC90,冬コミと夏コミなどどちらかに統一するか,併記するべき.

> マルチメディア
> DTM練習会2015
> 課題曲を作成して

課題曲を作成ではない気がする.
"課題に従って作曲して"

> 課題曲を作成して発表会を行う会と, 作曲講座を行う会を交互に行っています。

頭痛が痛いのかと思ったけど違った。
s/行う会/行う回/g
2箇所。

> 読書会

紹介文的にはすごいHここにありそう.

> 終焉のC++2015
> 『Effective C++』読書会。C++11, C++14, C++17 についての解説付きです。

この文を見る限りは本にC++17とかの解説が乗ってるように見えるけどその理解は正しいのだろうか。

> イベント
> NF

NF,November Festival,11月祭 の同一性がパッと見でわかるかな(わかりそう).
見出しが"11月祭(NF)"とかの方がいいのかもしれない.

> コミックマーケット

コミックマーケット,コミケ の同一性がパッと見でわかるかな(怪しい)
見出しが"コミックマーケット(コミケ)"とかの方がいいのかもしれない.
ただ,この辺はわかるでしょって感じで別に変えなくても良さそう.

> 合宿
> 春合宿
> 3 月, 一年の終わり

大胆. "年度の終わり"かなぁ. 別にいいけど.

> 最も多くの部員

最もではない気がする.非常に多くはあるけど.

> 新入生プロジェクト
> お絵かき練習プロジェクト 2016
> などなどまで

あまり聞かない表現なんだけど正しいんだろうか,正しかったらごめんなさい.

> 開催後は参加任意でご飯を食べにいきましょう～。

開催後って担当者以外にとって正しい表現なんだろうか.
"練習(会)後"とかかなぁ.

> 参加任意

"参加は任意"か"任意参加"かな気がする.

> DTM 練習会 2016
> 音楽理論やDTMについて教える小数点回を話しながら

おそらく s/話しながら/挟みながら/
"離しながら"ってのも不自然ですよね.

> 競技プログラミング練習会 2016 Normal
> KMC では 4 月より競技プログラミング練習会を行います。

この1文要らない気がする.(ただの好み)

> 使用できる言語は AOJ(会津オンラインジャッジ) で使える言語なら何でも構いません。

"使用できる言語は~で使える言語です。"か
"使用する言語は~で使える言語なら何でも構いません。"かの方が自然っぽい

> プログラミング未経験者の方

頭痛が痛い.
"未経験者"か"未経験の方"か
